"use client";
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {canvasSheet,sheetShiftsForGroup,label,compareSeniority,seniorityLabel,type State} from '@/lib/engine';

export function CanvasSheets({state,act,busy}:{state:State;act:(command:any)=>Promise<boolean>;busy:boolean}) {
 const [chosen,setChosen]=useState(''),[group,setGroup]=useState('all'),[search,setSearch]=useState(''),[date,setDate]=useState('');
 const id=chosen||state.current||state.canvases.at(-1)?.id;
 if(!id)return <section><h2>Dated canvas sheets</h2><p>Create a canvas to start its hours sheet.</p></section>;
 const report=canvasSheet(state,id),c=report.canvas;
 const fmt=(d:string)=>new Date(d+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
 const code=(kind:string)=>({'Accepted':'A','Refused':'R','Replacement':'Rep','Absence penalty':'P','Reversal':'Rev','Correction':'Adj'}[kind]||kind);
 return <section className="canvas-sheet"><div className="sheet-controls"><h2>Dated canvas sheets</h2><div className="columns"><label className="field"><span>Saved overtime period</span><select value={id} onChange={e=>{setChosen(e.target.value);setDate('');}}>{[...state.canvases].reverse().map(c=>{const r=canvasSheet(state,c.id);return <option value={c.id} key={c.id}>{fmt(r.start)} – {fmt(r.end)} · Canvas {c.canvassedOn?fmt(c.canvassedOn):'date not recorded'}</option>})}</select></label><label className="field"><span>RDO sheet</span><select value={group} onChange={e=>setGroup(e.target.value)}><option value="all">Both RDO groups</option><option value="FS">Friday–Saturday</option><option value="SM">Sunday–Monday</option></select></label></div><div className="actions"><label className="field"><span>Canvas performed on</span><Input type="date" value={date||c.canvassedOn||''} onInput={e=>setDate(e.currentTarget.value)}/></label><Button variant="outline" disabled={busy||!date} onClick={()=>act({type:'canvasDate',canvas:id,date})}>Save canvas date</Button><Button variant="outline" onClick={()=>window.print()}>Print sheet / Save PDF</Button><label className="field"><span>Find worker</span><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Worker name"/></label></div><p>Saved automatically with the canvas. Later corrections revise this period’s sheet and remain in History. Charges from other canvases do not change these totals.</p></div>
 {['FS','SM'].filter(g=>group==='all'||group===g).map(g=>{const visible=sheetShiftsForGroup(state,id,g),ids=new Set(visible.map(e=>e.id));return <div className="sheet-group" key={g}><h2>Shop overtime · {g==='FS'?'Friday–Saturday':'Sunday–Monday'} RDO</h2><p><b>Overtime: {fmt(report.start)} – {fmt(report.end)}</b> · Canvassed: {c.canvassedOn?fmt(c.canvassedOn):'Not recorded — enter above'}</p><p className="sheet-legend">A = accepted · R = refused · Rep = replacement · P = absence penalty · Rev = reversal · Adj = correction · — = no charge. Each shift shows net hours charged and the running total, in canvassing order.</p><div className="sheet-scroll"><table className="hours-sheet"><thead><tr><th rowSpan={2}>Seniority</th><th rowSpan={2}>Worker</th><th rowSpan={2}>Starting hours</th>{visible.map(e=><th colSpan={2} key={e.id}>{e.type}<br/>{label(e)}{e.canceled&&<><br/>CANCELED</>}</th>)}<th rowSpan={2}>Ending total</th></tr><tr>{visible.flatMap(e=>[<th key={e.id+'charge'}>Charged</th>,<th key={e.id+'total'}>Hours</th>])}</tr></thead><tbody>{report.rows.filter(r=>r.worker.rdo===g&&r.worker.name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>compareSeniority(a.worker,b.worker)).map(r=><tr key={r.worker.id}><td>{seniorityLabel(r.worker)}</td><th scope="row">{r.worker.name}</th><td>{r.opening}</td>{r.cells.filter(cell=>ids.has(cell.shift)).flatMap(cell=>[<td key={cell.shift+'charge'} className={cell.entries.some(e=>e.kind==='Refused')?'red':''}><b>{cell.entries.length?cell.hours:'—'}</b>{cell.entries.map(e=><small key={e.id}>{code(e.kind)} {e.hours>0?'+':''}{e.hours}</small>)}</td>,<td key={cell.shift+'total'}>{cell.running}</td>])}<td><b>{r.ending}</b></td></tr>)}</tbody></table></div></div>})}
 </section>;
}
